---
- hosts: controller
  become: yes
  vars_files:
    - vars/stacks/controller/vars.yml
  tasks:
    - name: install metricbeat
      tags: metricbeat
      block:
        - set_fact:
            es_hosts: "{{ ['http://monitor.lan:9200'] }}"

        - include_role:
            name: metricbeat
          vars:
            beat_hostname: "controller"
            elasticsearch_output_hosts: "{{ es_hosts }}"
    
    - name: mount drive
      tags:
        - drive
        - devices
      block:
        - set_fact:
            drives:
              - /media/mark/WD

        - name: mount HD
          include_role:
            name: devices
          vars:
            mountpoints: "{{ drives }}"
            fstype: ext4

        - name: chown dir
          file:
            path: "{{ item }}"
            state: directory
            recurse: yes
            owner: mark
            group: mark
          with_items: "{{ drives }}"
    
    - name: setup environment
      tags:
        - ansible
      include_role:
        name: ansible
    
    - name: configure update schedule
      tags:
        - update-schedule
      block:
        - name: ensure metricbeat is started on reboot
          cron:
            name: start metricbeat on reboot
            user: root
            job: docker start metricbeat
            special_time: reboot

        - name: configure update schedules
          cron:
            name: update {{ item.name }}
            user: mark
            weekday: "{{ item.weekday }}"
            hour: "{{ item.hour }}"
            minute: "{{ item.minute }}"
            job: /usr/local/bin/ansible-playbook /home/mark/home_cloud/update_playbook -i /home/mark/home_cloud/hosts.ini --tags "{{ item.name }}" --skip-tags meta
          with_items:
            - name: controller
              weekday: 0  # sunday
              hour: 8     # 2am central
              minute: 0
            - name: jellyfin
              weekday: 2  # tuesday
              hour: 8
              minute: 0
            - name: monitor
              weekday: 4  # thursday
              hour: 8
              minute: 0