---
- hosts: controller
  become: yes
  vars_files:
    - vars/stacks/controller/vars.yml
  tasks:
    - name: install metricbeat
      tags: metricbeat
      block:
        - set_fact:
            es_hosts: "{{ ['http://monitor.lan:9200'] }}"

        - include_role:
            name: metricbeat
          vars:
            beat_hostname: "controller"
            elasticsearch_output_hosts: "{{ es_hosts }}"
    
    - name: mount drive
      tags:
        - drive
        - devices
      block:
        - set_fact:
            drives:
              - /media/mark/WD

        - name: mount HD
          include_role:
            name: devices
          vars:
            mountpoints: "{{ drives }}"
            fstype: ext4

        - name: chown dir
          file:
            path: "{{ item }}"
            state: directory
            recurse: yes
            owner: mark
            group: mark
          with_items: "{{ drives }}"
    
    - name: setup environment
      tags:
        - ansible
      include_role:
        name: ansible