---
- hosts: jellyfin
  become: yes
  vars_files:
    - vars/stacks/jellyfin/vars.yml
  tasks:
    - name: define media
      set_fact:
        media: "{{ media_type | default('Movies') }}"
    
    - name: define ssd location
      set_fact:
        ssd: "{{ drive | default('ssd2') }}"
    
    - name: setup source location
      set_fact:
        source: "/media/mark/WD/Videos/{{ media }}/{{ src_dir }}/"
      when: src_dir is defined
    
    - name: setup source file
      set_fact:
        source: "/media/mark/WD/Videos/{{ media }}/{{ src_file }}"
      when: src_file is defined
    
    - name: setup destination location
      set_fact:
        destination: "/home/mark/{{ ssd }}/{{ media }}/{{ dst_dir | default('') }}"
    
    - debug:
        var: "{{ item }}"
      with_items:
        - source
        - destination
    
    - pause:
        prompt: "src and dest look okay?"

    - name: copy files
      copy:
        dest: "{{ destination }}"
        group: root
        owner: root
        mode: 0755
        src: "{{ source }}"
