---
# Install dockerized emby on raspberry pi 4 running ubuntu server

# Use:

# Deploying on clean ubuntu server
# - ansible-playbook emby_playbook.yml -i hosts.ini -e ansible_hosts=emby
#
# If docker is already installed
# - ansible-playbook emby_playbook.yml -i hosts.ini -e ansible_hosts=emby --skip-tags meta
#
# If media drives are already mounted
# - ansible-playbook emby_playbook.yml -i hosts.ini -e ansible_hosts=emby --skip-tags drives
#
# Once Emby is setup, snapshot the config directory and store offsite
# - ansible-playbook emby_playbook.yml -i hosts.ini -e ansible_hosts=emby --tags snapshot --skip-tags meta
#
# To use the snapshotted config directory on a fresh install
# - ansible-playbook emby_playbook.yml -i hosts.ini -e ansible_hosts=emby -e restore_snapshot=emby_backup-2022-02-07T04:30:10Z.tar.gz
########################################################################

- hosts: emby
  tags: install
  become: yes
  vars_files:
    - vars/stacks/emby/vars.yml
  tasks:
    - name: install emby
      include_role:
        name: emby

- hosts: emby
  tags: metricbeat
  become: yes
  vars_files:
    - vars/stacks/emby/vars.yml
  tasks:
    - name: install metricbeat
      tags: metricbeat
      block:
        - set_fact:
            es_hosts: "{{ ['http://' + item + ':9200'] + es_hosts|default([]) }}"
          with_items: "{{ groups['monitor'] }}"

        - include_role:
            name: metricbeat
          vars:
            beat_hostname: "emby"
            elasticsearch_output_hosts: "{{ es_hosts }}"

- hosts: emby
  tags:
    - never
    - backup
    - snapshot
  become: yes
  vars_files:
    - vars/stacks/emby/vars.yml
  tasks:
    - name: backup config directory
      include_role:
        name: emby
        tasks_from: snapshot

