---
- hosts: "{{ ansible_hosts }}"
  become: yes
  vars_files:
    - vars/stacks/{{ ansible_hosts }}/vars.yml
  tasks:
    - name: mount drive
      include_role:
        name: devices
      vars:
        mountpoints:
          - /media/mark/ssd1