---
- hosts: worker
  become: yes
  gather_facts: yes
  vars_files:
    - vars/stacks/worker/vars.yml
  tasks:
    - name: install metricbeat
      tags:
        - beats
        - metricbeat
      include_role:
        name: metricbeat
      vars:
        beat_hostname: "worker"
        elasticsearch_output_hosts:
          - http://monitor.lan:9200

    - name: setup openvpn
      tags:
        - openvpn
        - vpn
      include_role:
        name: openvpn
        tasks_from: client
    
    - name: install and configure qbittorrent
      tags:
        - torrent
        - bittorrent
        - qbittorrent
      include_role:
        name: qbittorrent
        tasks_from: main