---
- set_fact:
    dist_upgrade: "{{ upgrade_dist | default('no') }}"

- set_fact:
    upgrade_setting: safe
  when: not dist_upgrade

- set_fact:
    upgrade_setting: dist
  when: dist_upgrade

- name: Update apt-cache and do {{ upgrade_setting }} upgrade
  apt:
    update_cache: yes
    cache_valid_time: 3600
    upgrade: "{{ upgrade_setting }}"

- name: Check if reboot required
  stat:
    path: /var/run/reboot-required
  register: reboot_required_file

- debug:
    var: ansible_connection

- fail:
  when:
    - ansible_connection == 'local'

- name: Reboot if required
  reboot:
  when:
    - ansible_connection == 'ssh'
    - reboot_required_file.stat.exists == true

- name: Reboot if required
  command: init 6
  when:
    - ansible_connection == 'local'
    - reboot_required_file.stat.exists == true

- name: Wait for host to come back up
  pause:
    minutes: 2
  when: reboot_required_file.stat.exists == true