---
- name: pull kibana docker image
  docker_image:
    name: "{{ docker_image }}"
    tag: "{{ image_tag }}"
    source: pull
    state: present

- name: start kibana
  docker_container:
    image: "{{ docker_image }}:{{ image_tag }}"
    name: kibana
    restart: no
    auto_remove: no
    detach: yes
    network_mode: host
    env:
      ELASTICSEARCH_HOSTS: "http://monitor.lan:9200"