---
- debug:
    var: mountpoints

- name: verify that params are defined
  fail:
  when: mountpoints is not defined

- debug:
    var: fstype

- name: verify that params are defined
  fail:
  when: fstype is not defined

- name: verify at least one mountpoint
  fail:
  when: mountpoints | length < 1

- name: mount drives
  mount_drives:
    mountpoints: "{{ mountpoints }}"
  register: mount_result

- debug:
    var: mount_result

- set_fact:
    device_mappings: "{{ mount_result.devices | to_json }}"

- debug:
    var: device_mappings

- pause:
    prompt: "validate the mappings"

- name: mount the drives
  mount:
    src: "{{ item['device'] }}"
    path: "{{ item['mountpoint'] }}"
    state: mounted
    fstype: "{{ fstype }}"
    opts: rw,user,defaults
  with_items: "{{ device_mappings }}"
