---
- name: create directories
  file:
    path: {{ item }}
    state: directory
    recurse: yes
    owner: mark
    group: mark
  with_items:
    - "{{ config_directory }}"
    - "{{ downloads_directory }}"

- name: get uid and gid
  block:
    - name: run getent
      getent:
        database: passwd
        key: mark
    
    - name: get uid
      set_fact:
        uid: "{{ ansible_facts.getent_passwd.mark[1] }}"

    - name: get gid
      set_fact:
        gid: "{{ ansible_facts.getent_passwd.mark[2] }}"
    
    - debug:
        var: uid
    
    - debug:
        var: gid

- name: pull qbittorrent docker image
  docker_image:
    state: present
    tag: "{{ image_tag }}"
    name: "{{ docker_image }}"
    source: pull

- name: run qbittorrent server
  docker_container:
    image: "{{ docker_image }}:{{ image_tag }}"
    name: qbittorrent
    restart: yes
    restart_policy: on-failure
    restart_retries: 20
    auto_remove: no
    detach: yes
    env:
      PUID: "{{ uid | int }}"
      PGID: "{{ gid | int }}"
      WEBUI_PORT: 8080
      TZ: Europe/London
    network_mode: host
    mounts:
      - propagation: rshared
        read_only: no
        source: "{{ config_directory }}"
        target: /config
        type: bind
      - propagation: rshared
        read_only: no
        source: "{{ downloads_directory }}"
        target: /downloads
        type: bind