---
- debug:
    var: media_volumes

- debug:
    var: home_directory

- fail:
  when: media_volumes is not defined

- fail:
  when: media_volumes | length < 1

- fail:
  when: home_directory is not defined

- name: mount drives
  tags:
    - drives
    - devices
  include_role:
    name: devices
  vars:
    mountpoints: "{{ media_volumes }}"
    fstype: exfat

- name: create "{{ home_directory }}"
  file:
    path: "{{ home_directory }}"
    recurse: yes
    state: directory
    mode: 0755
    owner: root
    group: root

- name: restore "{{ home_directory }}"
  unarchive:
    src: "{{ local_backup_store }}{{ restore_snapshot }}"
    dest: "{{ home_directory }}"
    group: root
    owner: root
    mode: 0755
  when: restore_snapshot is defined

- set_fact:
    mounts:
      - propagation: rshared
        read_only: no
        source: "{{ home_directory }}"
        target: /config
        type: bind   

- set_fact:
    mounts: "{{ [{'propagation':'rshared','read_only':'no'|bool,'source':item,'target':'/volumes/'+item.split('/')[-1],'type':'bind'}] + mounts }}"
  with_items: "{{ media_volumes }}"

- debug:
    var: mounts

- name: restart docker
  service:
    name: docker
    state: restarted
    daemon_reload: yes

- name: pull emby docker image
  docker_image:
    state: present
    tag: "{{ image_tag }}"
    name: "{{ docker_image }}"
    source: pull

- name: run emby server
  docker_container:
    image: "{{ docker_image }}:{{ image_tag }}"
    name: embyserver
    restart: yes
    restart_policy: on-failure
    restart_retries: 20
    auto_remove: no
    detach: yes
    devices:
      - /dev/video10:/dev/video10
      - /dev/video11:/dev/video11
      - /dev/video12:/dev/video12
    env:
      UID: "{{ uid | default(0) | int }}"
      GID: "{{ gid | default(0) | int }}"
      GIDLIST: "{{ gidlist | default(0) | int }}"
    network_mode: host
    mounts: "{{ mounts }}"  


    
    