---
- name: install deps
  apt:
    force_apt_get: yes
    update_cache: yes
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
      - linux-modules-extra-raspi
    state: latest

- name: reboot
  reboot:
    reboot_timeout: 600
  when: restart_after_apt|default(true)

- name: add docker GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    keyring: /usr/share/keyrings/docker-archive-keyring.gpg

- name: get architecture
  shell: dpkg --print-architecture
  register: arch

- name: get release
  shell: lsb_release -cs
  register: release

- set_fact:
    deb_command: "deb [arch={{ arch.stdout }} signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu {{ release.stdout }} stable"

- debug:
    var: deb_command

- name: add stable repo to sources
  lineinfile:
    path: /etc/apt/sources.list.d/docker.list
    regexp: "^.+download.docker.com/linux/ubuntu.+"
    line: "{{ deb_command }}"
    create: yes

- name: stop openvpn
  service:
    name: openvpn-client@{{ vpn_config }}
    state: stopped
  when: vpn_config is defined

- name: install docker
  apt:
    force_apt_get: yes
    update_cache: yes
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: latest

- name: install docker SDK for python
  pip:
    executable: pip3
    name: docker
    state: latest

- name: start openvpn
  service:
    name: openvpn-client@{{ vpn_config }}
    state: started
  when: vpn_config is defined
    