---
git_repo: https://github.com/markditsworth/weather_monitor.git
contact_email: 
gmail_address: 
gmail_app_password: 
lat_lon: 
enable_forecast: true
forecast_hour: 10 # utc 5-6am central
forecast_job: docker run -d --rm --user python-user -v /home/mark/weather:/home/python-user:rw weather_monitor --forecast
enable_alerts: false
alert_minute: "*/5"
alert_job: docker run -d --rm --user python-user -v /home/mark/weather:/home/python-user:rw weather_monitor --alerts